### ISSUE TITLE
Linux Mint Cinnamon(x11)  顶部托盘图标一直显示为黑色

### ISSUE THREAD

**Issue by wrt97vedm2bpm5cefa2po4t** [flathub/io.github.qier222.YesPlayMusic#29]
系统信息如下：![图片](https://github.com/flathub/io.github.qier222.YesPlayMusic/assets/46921141/acce4e47-c12a-4fa0-9fa3-f436a3908ee7)

无论是浅色模式还是深色模式，托盘图标一直为黑色。
cinnamon的默认
![图片](https://github.com/flathub/io.github.qier222.YesPlayMusic/assets/46921141/2788e71a-6ac5-4476-ba6a-4fa00b6a85bd)

![图片](https://github.com/flathub/io.github.qier222.YesPlayMusic/assets/46921141/384afb4a-c4c8-476d-8947-3dfbac558884)

**Comment by madoka773** [comment]
尝试将系统的主题设置为暗色试试

**Comment by madoka773** [comment]
难搞哦，我这按这样设置的话是好的，不过这是 GNOME https://github.com/qier222/YesPlayMusic/issues/2196#issuecomment-2093106424
